name: Bug Report
description: Report a bug to help us improve.
title: "[Bug]: "
labels: [bug]
assignees: [Hamza417]

body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

    - type: input
      id: bug_description
      attributes:
          label: Bug Description
          description: A clear and concise description of what the bug is.
          placeholder: Describe the bug here
      validations:
          required: true

    - type: textarea
      id: steps_to_reproduce
      attributes:
          label: Steps to Reproduce
          description: |
              Steps to reproduce the behavior:
              1. Go to '...'
              2. Click on '....'
              3. Scroll down to '....'
              4. See error
          placeholder: List the steps here
      validations:
          required: true

    - type: input
      id: expected_behavior
      attributes:
          label: Expected Behavior
          description: A clear and concise description of what you expected to happen.
          placeholder: Describe the expected behavior here
      validations:
          required: true

    - type: textarea
      id: screenshots
      attributes:
          label: Screenshots
          description: If applicable, add screenshots to help explain your problem else N/A.
          placeholder: Provide links to screenshots here

    - type: input
      id: device_info
      attributes:
          label: Device Information
          description: |
              Please complete the following information:
              - Device: [e.g. Pixel 8]
              - OS: [e.g. Android 14]
          placeholder: Provide device information here
      validations:
          required: true

    - type: textarea
      id: additional_context
      attributes:
          label: Additional Context
          description: Add any other context about the problem here.
          placeholder: Provide additional context here
